# need 4 gpus

project: coconut
save_path: models
name: prosqa-coconut-gnn

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: data/prosqa_train.json
val_path: data/prosqa_valid.json
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01

use_graph: True
graph_encoder: gcn2
graph_dim: 256
graph_hidden_dim: 256
graph_input_dim: 259
graph_prefix_len: 4
align_loss_weight: 0.05
latent_injection: residual
graph_sidecar_root: data/prosqa_graphs
graph_dropout: 0.1
graph_projector_hidden: 256
graph_projector_dropout: 0.1
graph_prefix_dropout: 0.1
